#!/usr/bin/env bash
#a script that transfers a file from client to server
#accepts 4 parameters, the path to the file, ip, username, path to ssh privatekey
#error if less than 3 args are passed

if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
