#!/usr/bin/env bash
# installs nginx

sudo apt-get  update -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start
