#!/usr/bin/env bash
# install and configure haproxy on servers

sudo apt-get -y update
apt-get -y install haproxy

# configuration
server_config=\
"
frontend  front
        bind *:80
        mode http
        default_backend back
backend back
        balance roundrobin
        server 243402-web-01 18.206.206.189:80 check
        server 243402-web-02 54.86.9.156:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
