#!/usr/bin/env bash
#installing & configuring a load balancer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

server_config=\
"
frontend http
        bind *:80
        mode http
        default_backend servers
backend servers
        balance roundrobin
        server 243402-web-01 100.26.235.181:80 check
        server 243402-web-02 54.234.38.8:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
