#!/usr/bin/env bash
#displays 1 to 20

n=1
while [ $n -le 20 ]; do
	case $n in
		4)
			echo -e "4\nbad luck from China";;
		9)
			echo -e "9\nbad luck from Japan";;
		17)
			echo -e "17\nbad luck from Italy";;
		*)
			echo "$n";;
	esac
	((n++))
done
